import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Elisa Daolio - Arteterapeuta Milano",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      
      <body>{children}</body>
    </html>
  );
}
